name: build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: '8.0.200'
  TEST_PROJ: 'Otus.Teaching.PromoCodeFactory.UnitTests'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Go to src
      run: cd src

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build
      
    - name: Go to test project
      run: cd ${{ env.TEST_PROJ }}
    
    - name: Test
      run: dotnet test