name: build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TEST_PROJ: 'src/Otus.Teaching.PromoCodeFactory.UnitTests'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '3.1.x', '6.0.x' ]

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
      
    - name: Install dependencies, build and test
      working-directory: ${{ env.TEST_PROJ }}
      run: |
        dotnet restore
        dotnet build
        dotnet test